In [2]:
# museum camera streams live video of an eagle's nest
# a published study found 4 nests with one egg, 14 nests with two eggs, and 2 nests with three eggs
# find the probability that the camera will find two eggs in the first nest it inspects
# find the probability that it will find 3 nests in a row with one egg each
# find the average number of eggs per nest
# create a program that takes input to answer the questions above
from collections import Counter
import statistics
nests = [1]*4 + [2]*14 + [3]*2
total_nests = len(nests)
egg_counts = Counter(nests)
probability_two_eggs = egg_counts[2] / total_nests
probability_one_egg_three_nests = (egg_counts[1] / total_nests) ** 3
average_eggs_per_nest = statistics.mean(nests)
print(f"Probability of finding two eggs in the first nest: {probability_two_eggs:.4f}")
print(f"Probability of finding three nests in a row with one egg each: {probability_one_egg_three_nests:.4f}")
print(f"Average number of eggs per nest: {average_eggs_per_nest:.2f}")  


Probability of finding two eggs in the first nest: 0.7000
Probability of finding three nests in a row with one egg each: 0.0080
Average number of eggs per nest: 1.90


In [4]:
# create a matrix to answer the questions above
# matrix will be Nests x Eggs
# matrix values: 17-1, 29-2, 7-3
import numpy as np
matrix = np.zeros((3, 3), dtype=int)
matrix[0, 0] = 17  # 1 egg
matrix[1, 1] = 29  # 2 eggs
matrix[2, 2] = 7   # 3 eggs
print("Matrix representation of nests and eggs:")
print(matrix)

Matrix representation of nests and eggs:
[[17  0  0]
 [ 0 29  0]
 [ 0  0  7]]


In [5]:
# run the program above with the matrix values in the previous cell
total_nests_matrix = matrix.sum()
probability_two_eggs_matrix = matrix[1, 1] / total_nests
probability_one_egg_three_nests_matrix = (matrix[0, 0] / total_nests_matrix) ** 3
average_eggs_per_nest_matrix = (1 * matrix[0, 0] + 2 * matrix[1, 1] + 3 * matrix[2, 2]) / total_nests_matrix
print(f"(Matrix) Probability of finding two eggs in the first nest: {probability_two_eggs_matrix:.4f}")
print(f"(Matrix) Probability of finding three nests in a row with one egg each: {probability_one_egg_three_nests_matrix:.4f}")
print(f"(Matrix) Average number of eggs per nest: {average_eggs_per_nest_matrix:.2f}")

(Matrix) Probability of finding two eggs in the first nest: 1.4500
(Matrix) Probability of finding three nests in a row with one egg each: 0.0330
(Matrix) Average number of eggs per nest: 1.81
